### ISSUE TITLE
Create a Shield/Hat class

### ISSUE THREAD

**Issue by CrazyGecko** [openiolink/io-link-master-shield-hat-sw#18]
Currently, the hardware of the Shield/Hat is contained in the classes HardwareArduino and HardwareRaspberry. With an Shield/Hat class, the library could be more abstracted from the hardware.

**Comment by gammeter** [comment]
Duplicate of #27

**Comment by gammeter** [comment]
There is now an other solution so that the classes `HardwareArduino` and `HardwareRaspberry` are now obsolete.
- Pins and SPI are associated to either class `Max14819` or `Max14819_Port`
- Writing to `stdout` is done by a free function `print()`
- To wait, there is a free function `wait_ms()`.
