### ISSUE TITLE
Methods with no arguments

### ISSUE THREAD

**Issue by gammeter** [openiolink/io-link-master-shield-hat-sw#29]
In several modules in this library, there are methods with no arguments that are declared and/or defined like `methodname()` (empty argument list) and others like `methodname(void)`. This should be unified. But which variant is correct for the C++ programming language?  
I only know that in C a function with an empty argument list is implied to have one `int` argument where as `foo(void)` really has no argument.

**Comment by maehne** [comment]
In C++, you leave the parentheses empty if a function has no arguments.
