### ISSUE TITLE
potential logic error (`||` vs. `&&`)

### ISSUE THREAD

**Issue by gammeter** [openiolink/io-link-master-shield-hat-sw#46]
https://github.com/openiolink/io-link-master-shield-hat-sw/blob/b60d9b4059610b7c1cb9fa93252d0520cbdbab4c/src/board/Max14819.cpp#L201

Shouldn't there be a `&&` instead of the `||`?

**Comment by SecurityCheck** [comment]
No the current status is correct. This should continue as long as the communication is still running and time for a timeout has not been reached.
